### PR TITLE
Design improvements

### PR DESCRIPTION
**Pull request by miukimiu**
Just a few design improvements. We still need some styles for mobile screen sizes.

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hmm, why did you remove the glitches?

Also do you mind putting the text inside the cards back in roboto or sans serif? We find it a lot of people have issues reading things are not code in monospace, does that make sense?

Like in here only the export part would be monospace and the rest would be roboto
Screenshot 2020-03-28 at 12 24 37

**Comment by miukimiu** [comment]
Hey @SaraVieira! 

The code font issue was originated because I replaced all the `SimpleCard` with `Card` and the font inherited there was the `Inconsolata, monospace;`. If you notice in master the first `Card` use this font:

Screenshot 2020-03-28 at 13 42 29

But I'll change that. I agree that the text should not be a monospace font.


The reason I commented ou the **Glitches** is that they were originated an overflow issue on mobile. This can be actually solved with a `body {overflow-x: hidden;}`. But the idea of the **Glitches** was to create a parallax effect. So I might create another PR to solve this.

IMG_6170


Screenshot 2020-03-28 at 13 56 21

**Comment by SaraVieira** [comment]
Ohh that makes sense, but you can put them back as we won't announce it this weekend and we can make a parallax using framer motion :)

**Comment by SaraVieira** [comment]
This looks awesome! Waiting for an approve from rachel 👍

**Pull request merged**
